### ISSUE TITLE
Definir sprites e tilesets que serão utilizadas

### ISSUE THREAD

**Issue by althoff** [gpoesia/cmmi-game#15]
Definir todos os Sprites e Tilesets que serão usados em todo o jogo.
Para isso, deverá ser pesquisado pelo grupo, alguns exemplos. 

O grupo deve votar e escolher o melhor.

**Comment by marco-souza** [comment]
![black_and_white_new_tileset_by_spaceemotion-d2xufqu](https://cloud.githubusercontent.com/assets/4452113/2916521/1907639a-d6bc-11e3-9034-71844602c528.png)

Bem simples esse tileset, mas é uma ideia

**Comment by althoff** [comment]
Essa 'Issue' está 75% concluída. 
Para o minigame 1 faltam definir alguns sprites.
O minigame 2 possui as sprites e tilesets definidas.
