### ISSUE TITLE
Implementar nível 2

### ISSUE THREAD

**Issue by marco-souza** [gpoesia/cmmi-game#24]
Deve ser criado o nível 2
- Fica a critério do Par 1 definir se haverão mini-games e como serão esses mini-games.
- Deve-se cuidar também da integração entre os mini-games, caso haja.

**Comment by althoff** [comment]
Não existirão, em princípio. mini-games separados.
1. Os sprites e tilesets já foram definidos e montados.
2. Existe animação do personagem principal no ambiente de jogo.
3. Foram definidas as interações entre usuário e jogo.
4. Faltam: 

\- Implementar interações.
- Integrar com os demais níveis do game.

**Comment by althoff** [comment]
O nível 2 foi separado em sub-sessões (minigames), mas não existirão acessos direto para cada mini-game através do menu. Ou seja, ele deverá seguir o fluxo do nível 2 para jogar todos os níveis.

Ao sair no meio do jogo as informações do nível 2 serão perdidas.

Implementado:
- Será indicado para o usuário o local para onde ele deve seguir, através de uma exclamação, para iniciar sua tarefa.
- MiniGame 1: Reunião com o cliente : Completo
- MiniGame 2: Planejamento de tempo: 80% Completo
- MiniGame 3: Planejamento de risco: Não-Completo, planejado: Terminar hoje.
- MiniGame 4: Interagir com os programadores (Gerir Equipe e Acompanhar andamento do projeto): Não-Completo, planejado: Terminar hoje.

**Comment by althoff** [comment]
Completo.
Falta integrar.
